apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q066a7hpi-python
  janus-idp.io/tekton: q066a7hpi-python
  backstage.io/kubernetes-id: q066a7hpi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q066a7hpi-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
