apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q066a7hpi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q066a7hpi-python 
  name: q066a7hpi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q066a7hpi-python 
